// Code generated by snek; DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var tootCmd = &cobra.Command{
	Use:     "toot",
	Run:     tootCmdRun,
	Aliases: []string{"t"},
	Short:   "toot command",
	Long:    "long explanation",
}
var pootCmd = &cobra.Command{
	Use: "poot",
	Run: pootCmdRun,

	Short: "poot command",
	Long:  "long explanation",
}

func init() {
	rootCmd.AddCommand(tootCmd)

	tootCmd.Flags().StringP("turkey", "t", "", "gobble gobble")

	viper.BindPFlag("turkey", tootCmd.Flags().Lookup("turkey"))
	tootCmd.PersistentFlags().StringP("gooble", "g", "", "gobble gobble")

	rootCmd.AddCommand(pootCmd)

	pootCmd.Flags().StringP("turkey", "t", "", "gobble gobble")

	viper.BindPFlag("turkey", pootCmd.Flags().Lookup("turkey"))
	pootCmd.PersistentFlags().StringP("gooble", "g", "", "gobble gobble")

}
