// Code generated by snek; DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var exampleCmd = &cobra.Command{
	Use:     "example",
	Aliases: []string{"e"},
	Short:   "example command",
	Long:    "example of a generated parent flag",
}
var genCmd = &cobra.Command{
	Use:   "gen",
	Short: "gen examples",
	Long:  "generate example commands",
	Run:   genCmdRun,
}
var configCmd = &cobra.Command{
	Use:   "config",
	Short: "print an example snek.yaml config",
	Long:  "prints an example config",
	Run:   configCmdRun,
}

func init() {
	rootCmd.Flags().StringP("rootFlag", "r", "", "root flag example")
	rootCmd.AddCommand(exampleCmd)
	exampleCmd.Flags().StringP("flag", "a", "", "a string flag")
	viper.BindPFlag("flag", exampleCmd.Flags().Lookup("flag"))
	exampleCmd.PersistentFlags().StringP("persistent", "p", "", "a persistent string flag")
	exampleCmd.AddCommand(genCmd)
	exampleCmd.AddCommand(configCmd)
}
