// Code generated by snek; DO NOT EDIT.

package cmd

import (
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

type fooCmdT struct{ Cmd }

var fooCmd = &cobra.Command{
	Use:     "foo",
	Run:     fooCmdRun,
	Aliases: []string{"f"},
	Short:   "foo command",
	Long:    "long explanation",
}

type barCmdT struct{ Cmd }

var barCmd = &cobra.Command{
	Use: "bar",
	Run: barCmdRun,

	Short: "bar command",
	Long:  "this is a sub command of foo",
}

func init() {
	rootCmd.AddCommand(fooCmd)

	fooCmd.Flags().StringP("flag", "f", "", "a string flag")

	viper.BindPFlag("flag", fooCmd.Flags().Lookup("flag"))
	fooCmd.PersistentFlags().StringP("persistent", "p", "", "a persistent string flag")

	fooCmd.AddCommand(barCmd)

}
