// Code generated by "stringer -type Field"; DO NOT EDIT.

package cmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Aliases-0]
	_ = x[Flags-1]
	_ = x[Long-2]
	_ = x[Name-3]
	_ = x[Parent-4]
	_ = x[Run-5]
	_ = x[Short-6]
	_ = x[Use-7]
}

const _Field_name = "AliasesFlagsLongNameParentRunShortUse"

var _Field_index = [...]uint8{0, 7, 12, 16, 20, 26, 29, 34, 37}

func (i Field) String() string {
	if i < 0 || i >= Field(len(_Field_index)-1) {
		return "Field(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Field_name[_Field_index[i]:_Field_index[i+1]]
}
